language: node_js
node_js:
    - "5.0"
before_script:
    - npm install grunt-cli -g
    - npm install bower -g
    - npm install jasmine -g
    - bower install
notifications:
  email:
    recipients:
      - jean.daniel.michaud@gmail.com
        on_success: never
        on_failure: always
