language: node_js
node_js:
    - "5.0"
before_script:
    - npm install grunt-cli -g
    - npm install bower -g
    - npm install jasmine -g
    - bower install
    - cp patch/peg-0.9.0.js bower_components/pegjs/
notifications:
  email:
    recipients:
      - jean.daniel.michaud@gmail.com
      - jdmichaud@users.noreply.github.com
    on_success: change
    on_failure: always
addons:
    firefox: "latest"
